apiVersion: v1
kind: Service
metadata:
  name: dockube-sagnik-service
spec:
  selector:
    app: dockube-sagnik-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockube-sagnik-app
spec:
  selector:
    matchLabels:
      app: dockube-sagnik-app
  replicas: 3
  template:
    metadata:
      labels:
        app: dockube-sagnik-app
    spec:
      containers:
      - name: dockube-sagnik-app
        image: sagnikr/dockube-sagnik
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000